### ISSUE TITLE
Why `opt-level = 0` in Cargo.toml?

### ISSUE THREAD

**Issue by e00E** [mahkoh/uapi#4]
I am curious about
```toml
[profile.release.build-override]
opt-level = 0
```
in Cargo.toml.
According to https://doc.rust-lang.org/cargo/reference/profiles.html#build-dependencies this is already the default so what is the purpose of setting this there?
